// Generate prisma/seed.sql from the existing TS master data so it can be
// loaded with `wrangler d1 execute tabikomi-fares --local --file=...`.

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { CITIES } from '../src/data/cities'
import { SHINKANSEN_STATIONS } from '../src/data/shinkansen-stations'
import { REGIONS, regionOfPrefecture } from '../src/lib/regions'

function quote(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'NULL'
  return `'${value.replaceAll("'", "''")}'`
}

function num(value: number | null | undefined): string {
  if (value === null || value === undefined) return 'NULL'
  return String(value)
}

const lines: string[] = []
lines.push('-- Generated by scripts/build-seed-sql.ts; do not edit by hand.')
lines.push('-- Wipe known seed-owned tables before refilling.')
lines.push('DELETE FROM CityRailStation;')
lines.push('DELETE FROM ShinkansenStationProfile;')
lines.push('DELETE FROM RailStation;')
lines.push('DELETE FROM RailOperator;')
lines.push('DELETE FROM City;')
lines.push('DELETE FROM Region;')
lines.push('DELETE FROM BasicFareBand;')
lines.push('DELETE FROM ExpressFareBand;')
lines.push('DELETE FROM SurchargeFareBand;')

// --- Regions ---
const regionCodeFor: Record<string, string> = {
  北海道: 'hokkaido',
  東北: 'tohoku',
  関東: 'kanto',
  甲信越: 'koshinetsu',
  北陸: 'hokuriku',
  東海: 'tokai',
  近畿: 'kinki',
  中国: 'chugoku',
  四国: 'shikoku',
  '九州・沖縄': 'kyushu_okinawa'
}
for (const r of REGIONS) {
  lines.push(`INSERT INTO Region (code, name_ja) VALUES (${quote(regionCodeFor[r])}, ${quote(r)});`)
}

// --- Operators (JR 6 carriers split; private railways added in a later seed) ---
const JR_OPERATORS: { code: string; name_ja: string }[] = [
  { code: 'jr_east', name_ja: 'JR 東日本' },
  { code: 'jr_central', name_ja: 'JR 東海' },
  { code: 'jr_west', name_ja: 'JR 西日本' },
  { code: 'jr_hokkaido', name_ja: 'JR 北海道' },
  { code: 'jr_kyushu', name_ja: 'JR 九州' },
  { code: 'jr_shikoku', name_ja: 'JR 四国' }
]
for (const op of JR_OPERATORS) {
  lines.push(`INSERT INTO RailOperator (code, name_ja, kind) VALUES (${quote(op.code)}, ${quote(op.name_ja)}, 'jr');`)
}

// 新幹線 corridor → 代表運営 JR 社
// (跨ぐ corridor は最長運営区間の社を代表とする MVP 簡略化)
const CORRIDOR_TO_OPERATOR: Record<string, string> = {
  tokaido_sanyo_kyushu: 'jr_central',
  tohoku_hokkaido: 'jr_east',
  joetsu: 'jr_east',
  hokuriku: 'jr_east',
  yamagata: 'jr_east',
  akita: 'jr_east',
  nishi_kyushu: 'jr_kyushu'
}

// --- Cities ---
for (const c of CITIES) {
  const region = regionOfPrefecture(c.prefecture)
  if (!region) throw new Error(`unknown region for ${c.prefecture}`)
  const regionCode = regionCodeFor[region]
  lines.push(
    `INSERT INTO City (code, name_ja, prefecture, lat, lng, airport_iata, hotel_tier, region_code) VALUES (${quote(c.code)}, ${quote(c.name_ja)}, ${quote(c.prefecture)}, ${num(c.lat)}, ${num(c.lng)}, ${c.airport_iata ? quote(c.airport_iata) : 'NULL'}, 0, ${quote(regionCode)});`
  )
}

// --- Rail stations + Shinkansen profiles ---
for (const s of SHINKANSEN_STATIONS) {
  const op = CORRIDOR_TO_OPERATOR[s.corridor] ?? 'jr_east'
  lines.push(
    `INSERT INTO RailStation (code, name_ja, operator_code, lat, lng) VALUES (${quote(s.code)}, ${quote(s.name_ja)}, ${quote(op)}, NULL, NULL);`
  )
  lines.push(
    `INSERT INTO ShinkansenStationProfile (station_code, corridor, km_from_origin) VALUES (${quote(s.code)}, ${quote(s.corridor)}, ${num(s.km_from_origin)});`
  )
}

// --- City ↔ Station ---
for (const c of CITIES) {
  for (const sc of c.shinkansen_station_codes) {
    lines.push(`INSERT INTO CityRailStation (city_code, station_code) VALUES (${quote(c.code)}, ${quote(sc)});`)
  }
}

// --- Basic fare bands (本州 3 社 幹線) ---
const BASIC: { upTo: number; fare: number }[] = [
  { upTo: 3, fare: 150 },
  { upTo: 6, fare: 190 },
  { upTo: 10, fare: 200 },
  { upTo: 15, fare: 240 },
  { upTo: 20, fare: 330 },
  { upTo: 25, fare: 420 },
  { upTo: 30, fare: 510 },
  { upTo: 35, fare: 590 },
  { upTo: 40, fare: 680 },
  { upTo: 45, fare: 770 },
  { upTo: 50, fare: 860 },
  { upTo: 60, fare: 990 },
  { upTo: 70, fare: 1170 },
  { upTo: 80, fare: 1340 },
  { upTo: 90, fare: 1520 },
  { upTo: 100, fare: 1690 },
  { upTo: 120, fare: 1980 },
  { upTo: 140, fare: 2310 },
  { upTo: 160, fare: 2640 },
  { upTo: 180, fare: 3080 },
  { upTo: 200, fare: 3410 },
  { upTo: 220, fare: 3740 },
  { upTo: 240, fare: 4070 },
  { upTo: 260, fare: 4510 },
  { upTo: 280, fare: 4840 },
  { upTo: 300, fare: 5170 },
  { upTo: 340, fare: 5720 },
  { upTo: 380, fare: 6380 },
  { upTo: 420, fare: 6930 },
  { upTo: 460, fare: 7480 },
  { upTo: 500, fare: 8030 },
  { upTo: 540, fare: 8580 },
  { upTo: 580, fare: 9130 },
  { upTo: 620, fare: 9460 },
  { upTo: 660, fare: 10010 },
  { upTo: 700, fare: 10340 },
  { upTo: 740, fare: 10670 },
  { upTo: 780, fare: 11220 },
  { upTo: 820, fare: 11550 },
  { upTo: 860, fare: 11880 },
  { upTo: 900, fare: 12210 },
  { upTo: 940, fare: 12540 },
  { upTo: 980, fare: 12870 },
  { upTo: 1020, fare: 13200 },
  { upTo: 1060, fare: 13530 },
  { upTo: 1100, fare: 13860 },
  { upTo: 1140, fare: 14080 },
  { upTo: 1180, fare: 14410 },
  { upTo: 1220, fare: 14740 },
  { upTo: 1260, fare: 14960 },
  { upTo: 1300, fare: 15290 },
  { upTo: 1340, fare: 15510 },
  { upTo: 1380, fare: 15840 },
  { upTo: 1420, fare: 16060 },
  { upTo: 1460, fare: 16280 },
  { upTo: 1500, fare: 16500 }
]
// 本州 3 社 (jr_east / jr_central / jr_west) は同じ表
for (const op of ['jr_east', 'jr_central', 'jr_west']) {
  for (const b of BASIC) {
    lines.push(
      `INSERT INTO BasicFareBand (operator_code, up_to_km, fare_jpy) VALUES (${quote(op)}, ${num(b.upTo)}, ${num(b.fare)});`
    )
  }
}

// 三島会社 (北海道 / 九州 / 四国) の別表第 2 号 - JR 東海規則 別表第 2 号イ から
// JR 北海道線。MVP として代表的な距離帯のみ抜粋。九州・四国は同等の別表だが
// PDF 詳細投入は次フェーズ。当面は本州 3 社よりやや高めの近似で代用する。
const HOKKAIDO_BASIC: { upTo: number; fare: number }[] = [
  { upTo: 3, fare: 200 },
  { upTo: 6, fare: 250 },
  { upTo: 10, fare: 290 },
  { upTo: 15, fare: 340 },
  { upTo: 20, fare: 440 },
  { upTo: 25, fare: 540 },
  { upTo: 30, fare: 640 },
  { upTo: 40, fare: 850 },
  { upTo: 50, fare: 1130 },
  { upTo: 60, fare: 1290 },
  { upTo: 70, fare: 1490 },
  { upTo: 80, fare: 1680 },
  { upTo: 90, fare: 1890 },
  { upTo: 100, fare: 2100 },
  { upTo: 120, fare: 2420 },
  { upTo: 140, fare: 2860 },
  { upTo: 160, fare: 3300 },
  { upTo: 180, fare: 3740 },
  { upTo: 200, fare: 4070 },
  { upTo: 250, fare: 4510 },
  { upTo: 300, fare: 5500 },
  { upTo: 99999, fare: 6600 }
]
for (const b of HOKKAIDO_BASIC) {
  lines.push(
    `INSERT INTO BasicFareBand (operator_code, up_to_km, fare_jpy) VALUES ('jr_hokkaido', ${num(b.upTo)}, ${num(b.fare)});`
  )
}

// 九州・四国は MVP 暫定として 三島会社 (jr_hokkaido) より少し低め (本州との中間)
// 本格化時に各社の別表第 2 号系で書き換え
const KYUSHU_SHIKOKU_BASIC: { upTo: number; fare: number }[] = HOKKAIDO_BASIC.map((b) => ({
  upTo: b.upTo,
  fare: Math.round((b.fare * 0.93) / 10) * 10
}))
for (const op of ['jr_kyushu', 'jr_shikoku']) {
  for (const b of KYUSHU_SHIKOKU_BASIC) {
    lines.push(
      `INSERT INTO BasicFareBand (operator_code, up_to_km, fare_jpy) VALUES (${quote(op)}, ${num(b.upTo)}, ${num(b.fare)});`
    )
  }
}

// --- Express fare bands per corridor (自由席ベース; 指定席 = +530) ---
const EXPRESS: Record<string, { upTo: number; fare: number }[]> = {
  tokaido_sanyo_kyushu: [
    { upTo: 50, fare: 880 },
    { upTo: 100, fare: 1760 },
    { upTo: 150, fare: 2530 },
    { upTo: 200, fare: 2950 },
    { upTo: 300, fare: 4170 },
    { upTo: 400, fare: 4960 },
    { upTo: 500, fare: 5240 },
    { upTo: 600, fare: 5470 },
    { upTo: 700, fare: 5810 },
    { upTo: 800, fare: 6080 },
    { upTo: 900, fare: 6420 },
    { upTo: 1000, fare: 6700 },
    { upTo: 1100, fare: 7260 },
    { upTo: 1200, fare: 7480 },
    { upTo: 1300, fare: 7700 },
    { upTo: 1400, fare: 7920 },
    { upTo: 1500, fare: 8140 }
  ],
  tohoku_hokkaido: [
    { upTo: 50, fare: 1000 },
    { upTo: 100, fare: 1830 },
    { upTo: 150, fare: 2400 },
    { upTo: 200, fare: 3060 },
    { upTo: 300, fare: 4270 },
    { upTo: 400, fare: 5040 },
    { upTo: 500, fare: 5360 },
    { upTo: 600, fare: 5810 },
    { upTo: 700, fare: 6790 },
    { upTo: 800, fare: 7480 },
    { upTo: 900, fare: 7700 }
  ],
  joetsu: [
    { upTo: 50, fare: 1000 },
    { upTo: 100, fare: 1830 },
    { upTo: 150, fare: 2400 },
    { upTo: 200, fare: 3060 },
    { upTo: 300, fare: 4270 },
    { upTo: 400, fare: 5040 }
  ],
  hokuriku: [
    { upTo: 50, fare: 1000 },
    { upTo: 100, fare: 2050 },
    { upTo: 150, fare: 2640 },
    { upTo: 200, fare: 3270 },
    { upTo: 300, fare: 4480 },
    { upTo: 400, fare: 5250 },
    { upTo: 500, fare: 5570 }
  ],
  yamagata: [
    { upTo: 50, fare: 990 },
    { upTo: 100, fare: 1530 },
    { upTo: 150, fare: 2080 }
  ],
  akita: [
    { upTo: 50, fare: 990 },
    { upTo: 100, fare: 1530 },
    { upTo: 150, fare: 2080 }
  ],
  nishi_kyushu: [
    { upTo: 50, fare: 1000 },
    { upTo: 100, fare: 1760 }
  ]
}
for (const [corridor, bands] of Object.entries(EXPRESS)) {
  for (const b of bands) {
    lines.push(
      `INSERT INTO ExpressFareBand (corridor, up_to_km, fare_jpy) VALUES (${quote(corridor)}, ${num(b.upTo)}, ${num(b.fare)});`
    )
  }
}

// --- Surcharge bands (green / gran_class) ---
const GREEN: { upTo: number; fare: number }[] = [
  { upTo: 100, fare: 1300 },
  { upTo: 200, fare: 2800 },
  { upTo: 400, fare: 4190 },
  { upTo: 600, fare: 4710 },
  { upTo: 800, fare: 5400 },
  { upTo: 1000, fare: 6080 },
  { upTo: 99999, fare: 6630 }
]
const GRAN: { upTo: number; fare: number }[] = [
  { upTo: 100, fare: 6390 },
  { upTo: 200, fare: 7480 },
  { upTo: 400, fare: 9430 },
  { upTo: 600, fare: 10670 },
  { upTo: 800, fare: 12060 },
  { upTo: 99999, fare: 13180 }
]
for (const b of GREEN) {
  lines.push(
    `INSERT INTO SurchargeFareBand (category, up_to_km, fare_jpy) VALUES ('green', ${num(b.upTo)}, ${num(b.fare)});`
  )
}
for (const b of GRAN) {
  lines.push(
    `INSERT INTO SurchargeFareBand (category, up_to_km, fare_jpy) VALUES ('gran_class', ${num(b.upTo)}, ${num(b.fare)});`
  )
}

const out = join(process.cwd(), 'prisma', 'seed.sql')
writeFileSync(out, `${lines.join('\n')}\n`)
console.log(`[seed] wrote ${lines.length} statements to ${out}`)
